files:
  - path: configs/prometheus
    doc-path: configs/prometheus
    type: prometheus-scrape-config
  - path: configs/slo
    doc-path: configs/slo
    type: sloth-slo
output:
  individual: docs/
  aggregated: docs/docs.md
